name: Update generator api
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g jsdoc-to-markdown
      - name: Update jsdoc
        run: |
          git clone https://github.com/yeoman/generator.git ../generator
          mkdir -p api/generator
          cd api/generator
          jsdoc2md ../../../generator/lib/*.js > api.md
          jsdoc2md ../../../generator/lib/actions/*.js > actions.md
          jsdoc2md ../../../generator/lib/util/*.js > util.md
          git add .
          # git config --local user.email "marceloshima@gmail.com"
          # git config --local user.name "Marcelo Shima"
          git commit -a -m "Update generator api"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update generator api
          committer: Marcelo Shima <mshima@users.noreply.github.com>
          author: Marcelo Shima <mshima@users.noreply.github.com>
          title: 'Update generator api'
          body: |
            Update generator api
          labels: automated pr
          branch: api-generator
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"

